SOURCES += \
    $$PWD/abmdaolib.cpp \
    $$PWD/common/base/basecommon.cpp \
    $$PWD/common/base/baseentity.cpp \
    $$PWD/common/file/fileutils.cpp \
    $$PWD/common/json/jsonutils.cpp \
    $$PWD/common/log/easylogging++.cc \
    $$PWD/common/mysql/SqlUtils.cpp \
    $$PWD/config/config.cpp \
    $$PWD/config/dao/currentdatadao.cpp \
    $$PWD/config/entity/currentdata.cpp \
    $$PWD/runinfo/dao/runinfodesdao.cpp \
    $$PWD/runinfo/dao/runinfodrillstatsdao.cpp \
    $$PWD/runinfo/dao/runinfogeneraldao.cpp \
    $$PWD/runinfo/dao/runinfomatchedsystemstrackingdao.cpp \
    $$PWD/runinfo/dao/runinfomudstatsdao.cpp \
    $$PWD/runinfo/dao/runinfomwdstatsdao.cpp \
    $$PWD/runinfo/dao/runinforeliabilitydao.cpp \
    $$PWD/runinfo/entity/runinfodes.cpp \
    $$PWD/runinfo/entity/runinfodrillstats.cpp \
    $$PWD/runinfo/entity/runinfogeneral.cpp \
    $$PWD/runinfo/entity/runinfomatchedsystemstracking.cpp \
    $$PWD/runinfo/entity/runinfomudstats.cpp \
    $$PWD/runinfo/entity/runinfomwdstats.cpp \
    $$PWD/runinfo/entity/runinforeliability.cpp \
    $$PWD/toolParam/dao/abidao.cpp \
    $$PWD/toolParam/dao/dgrdao.cpp \
    $$PWD/toolParam/dao/hcimdao.cpp \
    $$PWD/toolParam/dao/pcddao.cpp \
    $$PWD/toolParam/dao/pospulserdao.cpp \
    $$PWD/toolParam/dao/toolparametersdao.cpp \
    $$PWD/toolParam/entity/abi.cpp \
    $$PWD/toolParam/entity/dgr.cpp \
    $$PWD/toolParam/entity/hcim.cpp \
    $$PWD/toolParam/entity/pcd.cpp \
    $$PWD/toolParam/entity/pospulser.cpp \
    $$PWD/toolParam/entity/toolparameters.cpp \
    $$PWD/well/dao/wellinfodao.cpp \
    $$PWD/well/dao/wellinfodistancesdao.cpp \
    $$PWD/well/dao/wellinfoformationdao.cpp \
    $$PWD/well/dao/wellinfogeneraldao.cpp \
    $$PWD/well/dao/wellinfolocationdao.cpp \
    $$PWD/well/dao/wellinfomatchedsystemstrackingdao.cpp \
    $$PWD/well/dao/wellinfopersonneldao.cpp \
    $$PWD/well/dao/wellinfosurveyinfodao.cpp \
    $$PWD/well/entity/wellinfo.cpp \
    $$PWD/well/entity/wellinfodistances.cpp \
    $$PWD/well/entity/wellinfoformation.cpp \
    $$PWD/well/entity/wellinfogeneral.cpp \
    $$PWD/well/entity/wellinfolocation.cpp \
    $$PWD/well/entity/wellinfomatchedsystemstracking.cpp \
    $$PWD/well/entity/wellinfopersonnel.cpp \
    $$PWD/well/entity/wellinfosurveyinfo.cpp


HEADERS += \
    $$PWD/ABMDaoLib_global.h \
    $$PWD/abmdaolib.h \
    $$PWD/common/base/basecommon.h \
    $$PWD/common/base/baseentity.h \
    $$PWD/common/file/fileutils.h \
    $$PWD/common/json/jsonutils.h \
    $$PWD/common/log/easylogging++.h \
    $$PWD/common/mysql/SqlUtils.h \
    $$PWD/config/config.h \
    $$PWD/config/dao/currentdatadao.h \
    $$PWD/config/entity/currentdata.h \
    $$PWD/runinfo/dao/runinfodesdao.h \
    $$PWD/runinfo/dao/runinfodrillstatsdao.h \
    $$PWD/runinfo/dao/runinfogeneraldao.h \
    $$PWD/runinfo/dao/runinfomatchedsystemstrackingdao.h \
    $$PWD/runinfo/dao/runinfomudstatsdao.h \
    $$PWD/runinfo/dao/runinfomwdstatsdao.h \
    $$PWD/runinfo/dao/runinforeliabilitydao.h \
    $$PWD/runinfo/entity/runinfodes.h \
    $$PWD/runinfo/entity/runinfodrillstats.h \
    $$PWD/runinfo/entity/runinfogeneral.h \
    $$PWD/runinfo/entity/runinfomatchedsystemstracking.h \
    $$PWD/runinfo/entity/runinfomudstats.h \
    $$PWD/runinfo/entity/runinfomwdstats.h \
    $$PWD/runinfo/entity/runinforeliability.h \
    $$PWD/toolParam/dao/abidao.h \
    $$PWD/toolParam/dao/dgrdao.h \
    $$PWD/toolParam/dao/hcimdao.h \
    $$PWD/toolParam/dao/pcddao.h \
    $$PWD/toolParam/dao/pospulserdao.h \
    $$PWD/toolParam/dao/toolparametersdao.h \
    $$PWD/toolParam/entity/abi.h \
    $$PWD/toolParam/entity/dgr.h \
    $$PWD/toolParam/entity/hcim.h \
    $$PWD/toolParam/entity/pcd.h \
    $$PWD/toolParam/entity/pospulser.h \
    $$PWD/toolParam/entity/toolparameters.h \
    $$PWD/well/dao/wellinfodao.h \
    $$PWD/well/dao/wellinfodistancesdao.h \
    $$PWD/well/dao/wellinfoformationdao.h \
    $$PWD/well/dao/wellinfogeneraldao.h \
    $$PWD/well/dao/wellinfolocationdao.h \
    $$PWD/well/dao/wellinfomatchedsystemstrackingdao.h \
    $$PWD/well/dao/wellinfopersonneldao.h \
    $$PWD/well/dao/wellinfosurveyinfodao.h \
    $$PWD/well/entity/wellinfo.h \
    $$PWD/well/entity/wellinfodistances.h \
    $$PWD/well/entity/wellinfoformation.h \
    $$PWD/well/entity/wellinfogeneral.h \
    $$PWD/well/entity/wellinfolocation.h \
    $$PWD/well/entity/wellinfomatchedsystemstracking.h \
    $$PWD/well/entity/wellinfopersonnel.h \
    $$PWD/well/entity/wellinfosurveyinfo.h
