#ifndef SERIALPORTLIB_GLOBAL_H
#define SERIALPORTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALPORTLIB_LIBRARY)
#  define SERIALPORTLIB_EXPORT Q_DECL_EXPORT
#else
#  define SERIALPORTLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALPORTLIB_GLOBAL_H
